name: deploy-gh-pages

on:
  push: {branches: [main, master]}
  pull_request: {branches: [main, master]}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Disable etelemetry
      run: echo "NO_ET=TRUE" >> $GITHUB_ENV
    - name: Active conda env pydra-tutorial
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pydra-tutorial
        environment-file: etc/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - name: Install dependencies
      run: conda install -c conda-forge jupyter-book
    - name: Build JupyterBook
      run: jb build -W jupyterbook
    - uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: jupyterbook/_build/html
