name: Pydra

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9, '3.10']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Disable etelemetry
      run:  echo "NO_ET=TRUE" >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pydra-tutorial
        environment-file: etc/environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
           
    - name: Convert all md files to ipynb
      run: jupytext notebooks/*.md --to ipynb
    - name: Test notebooks with pytest
      run: pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/
